server:
  port: 8086

spring:
  application:
    name: AUTH-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

jwt:
  secret: MySuperSecretKeyForJwtWhichShouldBeLongEnough12345
  expiration: 86400000

user-service:
  url: http://localhost:8081

# =========================
# Eureka client config
# =========================
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
